'use client'
import { TutorialGame } from "./tutorialGame"
import "./tutorial.css"

import { useRef, useState } from "react";
import { settingsType, sMap } from "@/utils/helperTypes";


export default function Tutorial() {
    const audioRef = useRef<HTMLAudioElement>(null);
    const [audioReady, setAudioReady] = useState<boolean>(false);
    const gameMap : sMap = (
        [
            [
              27625,
              "SL"
            ],
            [
              28187.5,
              "SL"
            ],
            [
              28812.5,
              "SL"
            ],
            [
              29437.5,
              "SL"
            ],
            [
              30062.5,
              "SR"
            ],
            [
              30687.5,
              "SR"
            ],
            [
              31312.5,
              "SR"
            ],
            [
              31937.5,
              "SR"
            ],
            [
              32562.5,
              "FL"
            ],
            [
              33187.5,
              "FL"
            ],
            [
              33812.5,
              "FL"
            ],
            [
              34437.5,
              "FL"
            ],
            [
              35125,
              "FR"
            ],
            [
              35687.5,
              "FR"
            ],
            [
              36312.5,
              "FR"
            ],
            [
              36937.5,
              "FR"
            ],
            [
              47562.5,
              "ST"
            ],
            [
              48187.5,
              "FT"
            ],
            [
              48812.5,
              "ST"
            ],
            [
              49437.5,
              "FT"
            ],
            [
              50062.5,
              "ST"
            ],
            [
              50687.5,
              "FT"
            ],
            [
              51312.5,
              "ST"
            ],
            [
              51937.5,
              "FT"
            ],
            [
              52562.5,
              "ST"
            ],
            [
              53187.5,
              "FT"
            ],
            [
              53812.5,
              "ST"
            ],
            [
              54437.5,
              "FT"
            ],
            [
              55062.5,
              "ST"
            ],
            [
              55687.5,
              "FT"
            ],
            [
              56312.5,
              "ST"
            ],
            [
              56875,
              "FT"
            ],
            [
              57500,
              "FR"
            ],
            [
              57875,
              "FR"
            ],
            [
              58250,
              "FR"
            ],
            [
              58750,
              "SL"
            ],
            [
              59125,
              "SL"
            ],
            [
              59500,
              "SL"
            ],
            [
              67625,
              "SR"
            ],
            [
              68250,
              "SR"
            ],
            [
              68812.5,
              "SR"
            ],
            [
              69437.5,
              "FT"
            ],
            [
              70062.5,
              "FR"
            ],
            [
              70687.5,
              "FR"
            ],
            [
              71312.5,
              "FR"
            ],
            [
              72000,
              "ST"
            ],
            [
              72562.5,
              "SL"
            ],
            [
              73187.5,
              "FT"
            ],
            [
              73812.5,
              "FR"
            ],
            [
              74437.5,
              "ST"
            ],
            [
              75062.5,
              "SL"
            ],
            [
              75687.5,
              "SL"
            ],
            [
              76312.5,
              "SL"
            ],
            [
              77000,
              "FT"
            ],
            [
              77562.5,
              "FR"
            ],
            [
              78187.5,
              "FR"
            ],
            [
              78812.5,
              "FR"
            ],
            [
              79500,
              "ST"
            ],
            [
              80062.5,
              "FT"
            ],
            [
              80687.5,
              "ST"
            ],
            [
              81312.5,
              "FT"
            ],
            [
              81937.5,
              "ST"
            ],
            [
              82562.5,
              "SL"
            ],
            [
              83187.5,
              "SR"
            ],
            [
              83812.5,
              "SL"
            ],
            [
              84437.5,
              "FT"
            ],
            [
              85125,
              "FR"
            ],
            [
              85750,
              "FL"
            ],
            [
              86375,
              "FR"
            ],
            [
              86937.5,
              "ST"
            ],
            [
              87625,
              "FT"
            ],
            [
              88250,
              "ST"
            ],
            [
              88562.5,
              "SR"
            ],
            [
              88687.5,
              "SL"
            ],
            [
              89250,
              "FL"
            ],
            [
              89375,
              "FR"
            ],
            [
              89875,
              "SR"
            ],
            [
              90000,
              "SL"
            ],
            [
              90500,
              "FL"
            ],
            [
              90625,
              "FR"
            ],
            [
              91125,
              "SR"
            ],
            [
              91250,
              "SL"
            ],
            [
              91750,
              "FL"
            ],
            [
              91875,
              "FR"
            ],
            [
              92375,
              "SR"
            ],
            [
              92500,
              "SL"
            ],
            [
              93000,
              "FL"
            ],
            [
              93125,
              "FR"
            ],
            [
              93625,
              "SR"
            ],
            [
              93750,
              "SL"
            ],
            [
              94250,
              "FL"
            ],
            [
              94375,
              "FR"
            ],
            [
              94875,
              "SR"
            ],
            [
              95000,
              "SL"
            ],
            [
              95500,
              "FL"
            ],
            [
              95625,
              "FR"
            ],
            [
              96125,
              "SR"
            ],
            [
              96250,
              "SL"
            ],
            [
              97000,
              "FT"
            ],
            [
              97625,
              "ST"
            ],
            [
              98250,
              "FT"
            ],
            [
              98875,
              "ST"
            ],
            [
              99500,
              "FT"
            ],
            [
              100125,
              "FR"
            ],
            [
              100750,
              "FL"
            ],
            [
              101375,
              "FR"
            ],
            [
              102000,
              "ST"
            ],
            [
              102625,
              "SL"
            ],
            [
              103250,
              "SR"
            ],
            [
              103875,
              "SL"
            ],
            [
              104500,
              "FT"
            ],
            [
              105125,
              "FL"
            ],
            [
              105750,
              "FR"
            ],
            [
              107000,
              "ST"
            ]
          ]
)

    const defaultSettings :settingsType = {
        lLane: "J",
        rLane: "L",
        lTurn: "A",
        rTurn: "D",
        
        pause: "Escape",
        restart: "P",

        scrollSpd: 1500,

        gpVolume: 1,
        hsVolume: 0.5,

        offset: 0,

        backgroundDim: 0.5,
        mobileControls: false
    }

    const tutorialLength = 111;
    
    const handleSongReady = () => {
        console.log("Song is Ready", audioReady)
        setAudioReady(true)
    }
    
      const handleSongError = () => {
        setAudioReady(false);
    } 
    return (
        <div id="tutorial_wrapper">
            <div id="tutorial_screen">
                <audio 
                    src={"https://9boushb4a7.ufs.sh/f/9Jv1QVILGRy4TSL467Rdtrp40vKGHsZhwOBSRFICzN537olE"} 
                    controls={false} 
                    ref={audioRef} 
                    loop={false} 
                    onCanPlayThrough={handleSongReady}
                    onError={handleSongError}
                />
                <TutorialGame gameMap={gameMap} settings={defaultSettings} audioProp={audioRef} gameLength={tutorialLength}/>
            </div>
        </div>

    )
    
}