/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 project-tape-scene.glb --transform 
Files: project-tape-scene.glb [592.64KB] > C:\Users\13478\Documents\Blender Stuff\project-tape-scene-transformed.glb [43.47KB] (93%)
*/
import * as THREE from 'three'

import React from 'react'
// import { useGLTF, useAnimations } from '@react-three/drei'
import { useGLTF } from '@react-three/drei'

export function PSRoom(props) {
  const wireframeMaterial = new THREE.MeshBasicMaterial({ color: 'white', wireframe: true });

  const group = React.useRef()
  // const { nodes, materials, animations } = useGLTF('/project-tape-scene-transformed.glb')
  // const { actions } = useAnimations(animations, group)
  const { nodes } = useGLTF('/project-tape-scene-transformed.glb')
  // const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} scale={2}>
      <group name="Scene">
        <mesh name="CasTable" geometry={nodes.CasTable.geometry} material={wireframeMaterial} position={[6.337, -0.132, 11.236]} rotation={[0, -1.571, 0]} />
        <group name="CTray" position={[6.926, 2.231, 12.784]} scale={[1, 1, 2.351]}>
          <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={wireframeMaterial} />
          <mesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={wireframeMaterial}/>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/project-tape-scene-transformed.glb')
