/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 project-tape-scene.glb --transform 
Files: project-tape-scene.glb [387.37KB] > C:\Users\13478\Documents\Blender Stuff\project-tape-scene-transformed.glb [82.57KB] (79%)
*/
import * as THREE from 'three'

import React from 'react'
// import { useGLTF, useAnimations } from '@react-three/drei'
import { useGLTF } from '@react-three/drei'

export function PSRoom(props) {
  const wireframeMaterial = new THREE.MeshBasicMaterial({ color: 'white', wireframe: true });
  const group = React.useRef()
  const { nodes, materials } = useGLTF('/project-tape-scene-transformed.glb')
  // const { nodes, materials, animations } = useGLTF('/project-tape-scene-transformed.glb')
  // const { actions } = useAnimations(animations, group)
  // Experimenting with wireframe look. Like vib-ribbon
  return (
    // <group ref={group} {...props} dispose={null} scale={2}>
    //   <group name="Scene">
    //     <group name="Room" position={[9.88, 0.2, 16.274]} scale={[12.327, 12.327, 7.448]}>
    //       <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={wireframeMaterial} />
    //       <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.Wall_Texture} />
    //     </group>
    //     <mesh name="CasTable" geometry={nodes.CasTable.geometry} material={materials.Table_Texture} position={[6.337, -0.132, 11.236]} rotation={[0, -1.571, 0]} />
    //     <mesh name="Couch" geometry={nodes.Couch.geometry} material={materials.Couch_Texture} position={[15.898, -0.157, 20.654]} rotation={[0, 1.571, 0]} />
    //     <mesh name="CPlayer" geometry={nodes.CPlayer.geometry} material={materials.CPlayer_Texture} position={[6.926, 2.231, 12.748]} rotation={[0, 0.014, 0]} scale={[1, 1, 2.351]} />
    //     <mesh name="Computer" geometry={nodes.Computer.geometry} material={materials['Computer Texture']} position={[-0.968, 0.115, 17.013]} scale={[12.327, 12.327, 7.448]} />
    //     <group name="CTray" position={[6.926, 2.231, 12.784]} scale={[1, 1, 2.351]}>
    //       <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials.CPlayer_Texture} />
    //       <mesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials['Material.002']} />
    //     </group>
    //   </group>
    // </group>
    <group ref={group} {...props} dispose={null} scale={2}>
      <group name="Scene">
        <group name="Room" position={[9.88, 0.2, 16.274]} scale={[12.327, 12.327, 7.448]}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={wireframeMaterial} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={wireframeMaterial} />
        </group>
        <mesh name="CasTable" geometry={nodes.CasTable.geometry} material={wireframeMaterial} position={[6.337, -0.132, 11.236]} rotation={[0, -1.571, 0]} />
        <mesh name="Couch" geometry={nodes.Couch.geometry} material={wireframeMaterial} position={[15.898, -0.157, 20.654]} rotation={[0, 1.571, 0]} />
        <mesh name="CPlayer" geometry={nodes.CPlayer.geometry} material={wireframeMaterial} position={[6.926, 2.231, 12.748]} rotation={[0, 0.014, 0]} scale={[1, 1, 2.351]} />
        <mesh name="Computer" geometry={nodes.Computer.geometry} material={wireframeMaterial} position={[-0.968, 0.115, 17.013]} scale={[12.327, 12.327, 7.448]} />
        <group name="CTray" position={[6.926, 2.231, 12.784]} scale={[1, 1, 2.351]}>
          <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={wireframeMaterial} />
          <mesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={wireframeMaterial} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/project-tape-scene-transformed.glb')
